### ISSUE TITLE
'sae --help' doesn't work

### ISSUE THREAD

**Issue by moodwolfe** [DoctorRyner/sae#1]
<img width="303" alt="Снимок экрана 2019-12-17 в 02 13 30" src="https://user-images.githubusercontent.com/58894602/70951084-80a75800-2073-11ea-9375-39e809849034.png">

**Comment by DoctorRyner** [comment]
Thanks! Fixed in 11922d4dd8b03d9686fce0b71f142cfcd07e42d8
